### ISSUE TITLE
Movie can have more same categories on the back end 

### ISSUE THREAD

**Issue by TomassSimko** [TomassSimko/Private-Movie-Collection#12]
Maybe look also into the on delete cascade :)

![Screenshot_2023-01-07_at_19 49 32](https://user-images.githubusercontent.com/72190589/211166445-adc8ab7f-5160-47c7-8f66-0d76e9c1a7be.png)

**Comment by TomassSimko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A movie can have multiple same categories](https://trello.com/c/IKJnMCaF/55-a-movie-can-have-multiple-same-categories)

**Comment by patrikvalentiny** [comment]
Not an issue
