### ISSUE TITLE
Is this really necessary ? 

### ISSUE THREAD

**Issue by TomassSimko** [TomassSimko/Private-Movie-Collection#25]
![Screenshot 2023-01-10 at 18 17 13](https://user-images.githubusercontent.com/72190589/211618662-a6f6b0a1-f73c-480d-9afa-dd5ce44a4e91.png)

Why are we deleting the CatMovie also ? 
Is this necessary since we are having on delete cascade so that It wont leave anything behind when the movie is deleted ? 

Its it located in MovieDAO starting 154 ?

**Comment by LordStacker** [comment]
fixed on daily meeting 11-01
