### ISSUE TITLE
Update to use notification helper

### ISSUE THREAD

**Issue by TomassSimko** [TomassSimko/Private-Movie-Collection#30]
![Screenshot 2023-01-10 at 20 07 05](https://user-images.githubusercontent.com/72190589/211639650-f452e59f-fa77-491c-9c6a-3430c0c6f551.png)

Just reminder to put notification helper that is in the newest pr 
https://github.com/TomassSimko/Private-Movie-Collection/pull/29

**Comment by patrikvalentiny** [comment]
I would maybe keep it as it is since I am creating custom buttons and well as setting text for both content and header, but am open to discussion

**Comment by TomassSimko** [comment]
done
